<a href="https://colab.research.google.com/github/abhi-glitchhg/Intro-to-ml-dl/blob/main/Week1/Lecture1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Note: - In the first lecture, strings and lists were covered. 

#Welcome
 
In this notebook, we will be covering basic datatypes available in python3

In [ ]:
!python --version

Python 3.7.12


In [ ]:
print("Hello world")

Hello world


In [ ]:
print("Any random stuff here!")
print(2)

Any random stuff here!
2


###Rules for Defining Python Variables

*   A variable name must start with a letter or the underscore character
*   A variable name cannot start with a number
*   A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
*   Variable names are case-sensitive. 


In [ ]:
#following are valid ways of defining variables
variable1 = 5
varia_ble2 = "python"
___var____ = "var"
age = 2

In [ ]:
#invalid ways.. (here ipython also marks it red indicating this is error..)
1sas = "error"
es@4 = 0 


SyntaxError: ignored

In [ ]:
num1 = 3 #assignment operation
num2 = 4 

#Booleans

print(num1==3) # == is a comparison operator, if RHS and LHS are equal; it returns boolean value `True`, else returns false
print(num1>num2) 
print(num1<=num2) 



print("difference between num1 and num2 is ", num2-num1)
print("sum of num1 and num2 is ", num1+num2)
print("multiplication of num1 and num2 is ", num1*num2)

True
False
True
difference between num1 and num2 is  1
sum of num1 and num2 is  7
multiplication of num1 and num2 is  12


In [ ]:
id(3) == id(num1)

True

In [ ]:
print(9/2) # `/` is  normal division, output will be 4.5
print(9//2) #integer division ; only integer part of the division will be returned
print(9%2) # calculates remainder, here = 1 
print(9**2) #power operation 9^2 = 81;
print(9**3) #power operation, 9^3 = 729

4.5
4
1
81
729


#strings

## Operations on Strings -
Since strings are immutable, we can't change the value stored in a string

We can concatenate ('join') multiple strings.

Slice/substring operations

In [ ]:
string1 = "hello world"

In [ ]:
string1[2] = "L" #invalid

TypeError: ignored

## Indexing 



1.   Every charcater of the string can be accessed by it's position in the string.
2.   Indexing starts from zero.
3.   Syntax string_name[index_number] 




In [ ]:
#print h 
print(string1[0])

h


##Slicing operations

syntax - string[ start_index : stop_index : step ] #if you dont provide `start_index` , `stop_index`, or `step` default values will be used  

In [ ]:
#printing hello

string1[0:5] #only 0,1,2,3 and 4th index are printed, letter at 5th index is not printed 

'hello'

In [ ]:
string1[5] #returns string at 5th index i.e blank space

' '

In [ ]:
string1[2:] #slices string from 2nd index till the end of string, here we havent provided the index at which we have to stop, hence by default value is till end of the string 

'llo world'

In [ ]:
string1[3:] #slices string from 3rd index till the end,

'lo world'

In [ ]:
string1= "hello world"
string1[:5] #slices string from begining till 5th index (5th index is excluded)

'hello'

In [ ]:
string1[1:5] ##slices string from 1st index(second letter) till 5th index (5th index is excluded)

'ello'

In [ ]:
string1[1:-1] # -1 is the index of the last letter, -2 is the index of second last letter, and so on....

'ello worl'

In [ ]:
string1[2:-2]


'llo wor'

In [ ]:
print(string1[1:8:1])
print(string1[1:8]) #output is same as above, 
print(string1[1:8:3])
# string1[1:5:2] #start index : stop index : step 
# if no value for start index is given, slicing will begin from index 0, if no value for end index given, slicing will stop after the last letter, default value of step is 1. 

ello wo
ello wo
eoo


In [ ]:
string1[::4] #slices string from begining to end but with step of 2
# "hello world"

'hor'

In [ ]:
string1[:] #from beggining till the end, these are the default values for start index and stop index

'hello world'

In [ ]:
#concat
string1 = "hello world" #enter anything that you want!
string2 = string1 + " concat string" 

In [ ]:
string1 + " hello" # instead of +, try - ! 

'hello world hello'

In [ ]:
string1 *2 == string1 + string1 # == is comparator, returns true if the LHS is equal to RHS

True

In [ ]:
string3 = "abcdefgabcdefgsnje jsceckke" 

In [ ]:
string3.split("df") # no `df` substring in the above string, hence it will return whole string in a list...

['abcdefgabcdefgsnje jsceckke']

In [ ]:
#ord() function returns ASCII value of the character
print(ord("A"))


print(ord(" "))

65
32


for more about ascii, checkout - https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html

In [ ]:
#ASCII values 
# A = 65
# B = 66 
# C = 67
# z = 122

In [ ]:
double_string1 = string1*2  
double_string1

'hello worldhello world'

In [ ]:
double_string1.split("ll")

['he', 'o worldhe', 'o world']

In [ ]:
string1 + 71 #invalid because string and int cant be added together

TypeError: ignored

In [ ]:
int1 =71
int1

71

In [ ]:
str(int1)

'71'

In [ ]:
#we must type cast the int to string, 
string1+ str(71)

'hello world71'

#list

1. Initializing syntax: \n list_name = [value_1,value_2,...,value_n]
2. Behaviour Similar to strings
3. Mutable
4. Can contain multiple data types.

In [ ]:
list1 = ["1", 6, "a", 0.0003,2e-3] #objects in list can be of any type, (str,int,float,list)

print(list1)

['1', 6, 'a', 0.0003, 0.002]


In [ ]:
list1.append("vv")

In [ ]:
list1[3] = "1223829382y3827"

In [ ]:
list1

['1', 6, 'a', '1223829382y3827', 0.002, 'vv']

In [ ]:
list2 = ["333", 333]

In [ ]:
list1 += list2  #list1 = list1+ list2
list1

['1', 6, 'a', '1223829382y3827', 0.002, 'vv', '333', 333]

In [ ]:
list1[1] 

6

In [ ]:
list1[1] = 3 #replaces the element at the first index of the list1

In [ ]:
list1

['1', 3, 'a', '1223829382y3827', 0.002, 'vv', '333', 333]

In [ ]:
#add 
list2 = ["333", 333,]

In [ ]:
list3 = list1 + list2

In [ ]:
list3 

['1', 3, 'a', '1223829382y3827', 0.002, 'vv', '333', 333, '333', 333]

In [ ]:
list1 += list2 # list1 = list1 + list2 

In [ ]:
list1

['1', 3, 'a', '1223829382y3827', 0.002, 'vv', '333', 333, '333', 333]

In [ ]:
list1 * 3 == list1 + list1 +list1 
list1*3

['1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333,
 '1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333,
 '1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333]

In [ ]:
(3* list1)/3  #this will give an error
#not valid statement,

TypeError: ignored

In [ ]:
#append method for lists
list1.append("a") #will add "a" at the end of the list
list1.append( [ 3, "9"] ) # you can append any datatype object, try with int,str,float etc by yourself 

In [ ]:
list1

['1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333,
 'a',
 [3, '9']]

In [ ]:
#few methods of list that are handy
'''
1) append() - takes one input, that input is added to the end of the list
2) pop() - takes index position as an input, removes the object from memory at that index and returns the object, If no index given, it will remove the object at -1 index (last object in list)
3) index - takes one input and returns the index of the input in given array
'''
#read more here - https://www.w3schools.com/python/python_ref_list.asp


list1.index(333)

7

In [ ]:
list1

['1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333,
 'a',
 [3, '9']]

In [ ]:
animals = ['cat', 'dog', 'monkey']

In [ ]:
#print values in the list.. 

any_random_name = animals.pop() #removes 'monkey' from list and stored it in variable `any_random_name`
animals

['cat', 'dog']

In [ ]:
###Tuple and List are very similar datastructures. Only difference is that tuple is immutable (you cant edit it after defining)

animals = ('cat', 'dog', 'monkey') 
animals[1] = "elephant" #will give error because tuple is immutable.. 

TypeError: ignored

#Dictionary


Very useful datatype, keys are in left, values at right..

key-value pair, keys need to be unique

In [ ]:
player_price = [17,13,19]   #price in lakhs

player_name = ["sechin trendulkar","gautam gembhir","M doni"] 

player_price[player_name.index("gautam gembhir")] 

13

In [ ]:
player_name.index("gautam gembhir")

1

In [ ]:
player_price[player_name.index("gautam gembhir")]

13

In [ ]:
# but this is pain right?

In [ ]:
price_book = {"sechin trendulkar" : 17, "sechin trendulkar ":20} 

In [ ]:

price_book["gautam gembhir"] = 13
price_book["M doni"] =19



#dir(price_book) # dir function lists all the methods available for an object 

In [ ]:
list(price_book.items()) 

[('sechin trendulkar', 17),
 ('sechin trendulkar ', 20),
 ('gautam gembhir', 13),
 ('M doni', 19)]

In [ ]:
price_book2 = {"key1" :  2, }

In [ ]:
price_book # datatype - set 

{'M doni': 19,
 'gautam gembhir': 13,
 'sechin trendulkar': 17,
 'sechin trendulkar ': 20}

In [ ]:
#iteration in dictionary


for i in price_book.values():
  print(i)

for i in price_book.keys():
  print(i)

In [ ]:
tuple(price_book.items())



(('sechin trendulkar', 17),
 ('sechin trendulkar ', 20),
 ('gautam gembhir', 13),
 ('M doni', 19))

In [ ]:
for i in price_book.items():
  print("key is : ",i[0], ". value is ", i[1]) 

key is :  sechin trendulkar . value is  17
key is :  sechin trendulkar  . value is  20
key is :  gautam gembhir . value is  13
key is :  M doni . value is  19


In [ ]:
matrix = [
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],

          ]


for i,j,k in matrix:
  print(i, j, k)

('sechin trendulkar', 17)
('sechin trendulkar ', 20)
('gautam gembhir', 13)
('M doni', 19)


In [ ]:
i,j,k = [1,2,3]
type(i)

int

In [ ]:
print(a)

1


#If elif else



```
if x:
    if y:
        code-statement
elif z:  # else if
    another-code-statement
else:
    another-code-statement
```



In [ ]:
if True: # == is a comparator
  print("OMG this is true!")

OMG this is true!


In [ ]:
if  False:
  print("OMG this is false")

In [ ]:
if 1:
  print("OMG this is 1")

In [ ]:
if not 0: # not 0 
  print("OMG this is `not 0`")

OMG this is `not 0`


In [ ]:
if -1 : #everything other than 0 is mapped to true 
  print("true condition print hoga") #guess kro bhai 

else:
  print("false condition print hoga")

true condition print hoga


In [ ]:
x = False

if x:
    print('x was True!')
else:
    print('I will be printed in any case where x is not true')

I will be printed in any case where x is not true


In [ ]:
var = "a"

if var == "a" : 
  print("var is a")
  print("var is also a ")
if var == "b": # else if 
  print("var is b")
  print("some string")
if var == "c":
  print("var is c")
  print("c block is also executed")


var is a
var is also a 


In [ ]:
if 1 ==1 :
  print("true !!!!")
elif 2==2:
  print("hurray this also true!!!")

true !!!!


In [ ]:
var = "b" 

if var == "a" : 
  print("var is a")
elif var == "b": # else if 
  print("var is b")
elif var == "c":
  print("var is c")
  print("c block is also executed")
else: 
  print("Var is not a nor b")

var is b


#Loops 

Looping can be done over an iterable which can be a list, set, dictionary, etc.
Let us concern ourselves with lists for now.


range is one of the commonly used 


range(start, stop, step)

In [ ]:
a = list(range(-10,7,2))
a


[-10, -8, -6, -4, -2, 0, 2, 4, 6]

In [ ]:
b = list(range(2,10,2)) # step is 2, 10 will not be included
b

[2, 4, 6, 8]

In [ ]:
c= list(range(-10, 10, 3 )) #negative numbers are supported
c

[-10, -7, -4, -1, 2, 5, 8]

In [ ]:
d = list(range(2,10,-1)) #returns 
d

[]

In [ ]:
list(range(10, 1, -1))

[10, 9, 8, 7, 6, 5, 4, 3, 2]

In [ ]:
list(range(10,1,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2]

###Syntax - for loop 


```

for value in iterable:
    execute statement(s)
```



In [ ]:
a = [0, 1, 2, 3, 4, 5, 6]


for i in a:
  print(i,) 

0
1
2
3
4
5
6


In [ ]:
#a can be any iterable, i.e it can be a list, string, set, tuple 

a = (1, 2, 3, 4, 5, 6)

for  i in a:
  print(i)

1hihi 2hihi 3hihi 4hihi 5hihi 6hihi 

In [ ]:
a = "hello world"

for i in a:
  print(i)  

h
e
l
l
o
 
w
o
r
l
d


In [ ]:
matrix = [
          [1, 2, 3, 10],
          [4, 5, 6],
          [7, 8, 9],
          #{"1":2}
          ]


for sublist in matrix:
    print(sublist, " is a sublist")
    #sublist = "string" 
    for value in sublist:  #nested for loop 
        print(value , "is a value")
        

[1, 2, 3, 10]  is a sublist
1 is a value
2 is a value
3 is a value
10 is a value
[4, 5, 6]  is a sublist
4 is a value
5 is a value
6 is a value
[7, 8, 9]  is a sublist
7 is a value
8 is a value
9 is a value
{'1': 2}  is a sublist
1 is a value


In [ ]:
#reading abt break statement, continue statement and pass statement

#Functions

In [ ]:
def identity(input): #this identity function expects one object as an input; returns same thing, does nothing
  return input 

In [ ]:
identity(1.0)

1.0

In [ ]:
z1 = identity("something")
print(z1)

random_list = [1,2,3.4,"hello"] #
z2 = identity(random_list) #here you can see we have passed a list object to the identity function.
print(z2)

something
[1, 2, 3.4, 'hello']


In [ ]:
def add_numbers(x = 0  , y = 0, z=0): #in this function by default the input parameters are set to 0.
    print(z)
    return x+y+z

In [ ]:
add_numbers(x=3,z=2,y=2)

2


7

In [ ]:
type("strings")

str

In [ ]:
print(type(add_numbers))
print(add_numbers)

<class 'function'>
<function add_numbers at 0x7f6e1df44ef0>


In [ ]:
print(add_numbers(x=1,y=24))
print(add_numbers())

0
25
0
0


In [ ]:
new_func = add_numbers

new_func(x=1,y=24)


0


25

In [ ]:
a = 1.0


dir(a)

['__abs__',
 '__add__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__set_format__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 'as_integer_ratio',
 'conjugate',
 'fromhex',
 'hex',
 'imag',
 'is_integer',
 'real']

In [ ]:
#what if there are multiple inputs,add 5 numbers 

In [ ]:
def add_n_numbers(*args): #non keyword argument 
  sum=0
  print(args, type(args))
  for i in args:
    sum = sum+i
  return sum

In [ ]:
def add_n_numbers(*another_var):
  sum=0
  for i in another_var:
    sum = sum+i
  return sum

In [ ]:
add_n_numbers(1,2,33,5,6,67,4)

118

In [ ]:
visited_places = ["delhi", "chennai", "shillong", "Bits Pilani K K Birla Goa Campus"]

def last_visited(*args):
  print(args)
  return args[-1]

In [ ]:
last_visited(*visited_places) #using a star before a list unpacks the objects in the list

('delhi', 'chennai', 'shillong', 'Bits Pilani K K Birla Goa Campus')


'Bits Pilani K K Birla Goa Campus'

In [ ]:
def full_name(**kwargs):
  print(kwargs)
  return kwargs["name"]+kwargs["middle_name"]+ kwargs["last_name"]

In [ ]:
full_name(name = "ram ", last_name="patil",middle_name="shyam ")

{'name': 'ram ', 'last_name': 'patil', 'middle_name': 'shyam '}


'ram shyam patil'

In [ ]:
#list comprehension and lambda functions

#List of alphabets- normal way..

alphabets = []
for i in range(65,91):
  alphabets.append(chr(i))
alphabets



['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

In [ ]:
# using list comprehension 

alphabets = [chr(i) for i in range(65,91)]
alphabets

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

In [ ]:
my_func = lambda x,y : x**y
my_func(3,4)

81

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

Numpy is already installed in the google colab; so we dont have to install it seperately .

In [ ]:
import numpy 
import numpy as np


In [ ]:
a = numpy.array([1, 2, 3])  # Create a rank 1 array
print(a)
a[0] = 5                 # Change an element of the array
print(a)                  

[1 2 3]
[5 2 3]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = numpy.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.zeros((2,2))  # Create an array of all zeros
print(c)

[[0. 0.]
 [0. 0.]]


In [ ]:
c+2 #2 is added to every element


array([[2., 2.],
       [2., 2.]])

In [ ]:
print(a)
print(a+1)

[5 2 3]
[6 3 4]


In [ ]:
d = [1,2,3] 

d+1

TypeError: ignored

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
#index slicing in numpy
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
a*3 + 2

array([[ 5,  8, 11, 14],
       [17, 20, 23, 26],
       [29, 32, 35, 38]])