<a href="https://colab.research.google.com/github/abhi-glitchhg/Intro-to-ml-dl/blob/main/Week1/Lecture1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Note: - In the first lecture, strings and lists were covered. 

#Welcome
 
In this notebook, we will be covering basic datatypes available in python3

In [192]:
!python --version

Python 3.7.12


In [193]:
print("Hello world")

Hello world


In [194]:
print("Any random stuff here!")
print(2)

Any random stuff here!
2


###Rules for Defining Python Variables

*   A variable name must start with a letter or the underscore character
*   A variable name cannot start with a number
*   A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
*   Variable names are case-sensitive. 


In [195]:
#following are valid ways of defining variables
variable1 = 5
varia_ble2 = "python"
___var____ = "var"
age = 2

In [196]:
#invalid ways.. (here ipython also marks it red indicating this is error..)
1sas = "error"
es@4 = 0 


SyntaxError: ignored

In [197]:
num1 = 3 #assignment operation
num2 = 4 

#Booleans

print(num1==3) # == is a comparison operator, if RHS and LHS are equal; it returns boolean value `True`, else returns false
print(num1>num2) 
print(num1<=num2) 



print("difference between num1 and num2 is ", num2-num1)
print("sum of num1 and num2 is ", num1+num2)
print("multiplication of num1 and num2 is ", num1*num2)

True
False
True
difference between num1 and num2 is  1
sum of num1 and num2 is  7
multiplication of num1 and num2 is  12


In [198]:
id(3) == id(num1)

True

In [199]:
print(9/2) # `/` is  normal division, output will be 4.5
print(9//2) #integer division ; only integer part of the division will be returned
print(9%2) # calculates remainder, here = 1 
print(9**2) #power operation 9^2 = 81;
print(9**3) #power operation, 9^3 = 729

4.5
4
1
81
729


#strings


In [200]:
string1 = "hello world"

In [203]:
#printing hello

string1[0:5] #only 0,1,2,3 and 4th index are printed, letter at 5th index is not printed 

'hello'

In [204]:
string1[5] #returns string at 5th index i.e blank space

' '

In [205]:
string1[2:] #slices string from 2nd index till the end of string, here we havent provided the index at which we have to stop, hence by default value is till end of the string 

'llo world'

In [206]:
string1[3:] #slices string from 3rd index till the end,

'lo world'

In [207]:
string1= "hello world"
string1[:5] #slices string from begining till 5th index (5th index is excluded)

'hello'

In [208]:
string1[1:5] ##slices string from 1st index(second letter) till 5th index (5th index is excluded)

'ello'

In [209]:
string1[1:-1] # -1 is the index of the last letter, -2 is the index of second last letter, and so on....

'ello worl'

In [210]:
string1[2:-2]


'llo wor'

In [217]:
print(string1[1:8:1])
print(string1[1:8]) #output is same as above, 
print(string1[1:8:3])
# string1[1:5:2] #start index : stop index : step 
# if no value for start index is given, slicing will begin from index 0, if no value for end index given, slicing will stop after the last letter, default value of step is 1. 

ello wo
ello wo
eoo


In [218]:
string1[::4] #slices string from begining to end but with step of 2
# "hello world"

'hor'

In [219]:
string1[:] #from beggining till the end, these are the default values for start index and stop index

'hello world'

In [220]:
#concat
string1 = "hello world" #enter anything that you want!
string2 = string1 + " concat string" 

In [221]:
string1 + " hello" # instead of +, try - ! 

'hello world hello'

In [222]:
string1 *2 == string1 + string1 # == is comparator, returns true if the LHS is equal to RHS

True

In [223]:
string3 = "abcdefgabcdefgsnje jsceckke" 

In [224]:
string3.split("df") # no `df` substring in the above string, hence it will return whole string in a list...

['abcdefgabcdefgsnje jsceckke']

In [225]:
#ord() function returns ASCII value of the character
print(ord("A"))


print(ord(" "))

65
32


for more about ascii, checkout - https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html

In [226]:
#ASCII values 
# A = 65
# B = 66 
# C = 67
# z = 122

In [227]:
double_string1 = string1*2  
double_string1

'hello worldhello world'

In [228]:
double_string1.split("ll")

['he', 'o worldhe', 'o world']

In [229]:
string1 + 71 #invalid because string and int cant be added together

TypeError: ignored

In [230]:
int1 =71
int1

71

In [231]:
str(int1)

'71'

In [232]:
#we must type cast the int to string, 
string1+ str(71)

'hello world71'

#list


In [233]:
list1 = ["1", 6, "a", 0.0003,2e-3] #objects in list can be of any type, (str,int,float,list)

print(list1)

['1', 6, 'a', 0.0003, 0.002]


In [234]:
list1.append("vv")

In [235]:
list1[3] = "1223829382y3827"

In [236]:
list1

['1', 6, 'a', '1223829382y3827', 0.002, 'vv']

In [237]:
list2 = ["333", 333]

In [238]:
list1 += list2  #list1 = list1+ list2
list1

['1', 6, 'a', '1223829382y3827', 0.002, 'vv', '333', 333]

In [239]:
list1[1] 

6

In [240]:
list1[1] = 3 #replaces the element at the first index of the list1

In [241]:
list1

['1', 3, 'a', '1223829382y3827', 0.002, 'vv', '333', 333]

In [242]:
#add 
list2 = ["333", 333,]

In [243]:
list3 = list1 + list2

In [244]:
list3 

['1', 3, 'a', '1223829382y3827', 0.002, 'vv', '333', 333, '333', 333]

In [245]:
list1 += list2 # list1 = list1 + list2 

In [246]:
list1

['1', 3, 'a', '1223829382y3827', 0.002, 'vv', '333', 333, '333', 333]

In [247]:
list1 * 3 == list1 + list1 +list1 
list1*3

['1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333,
 '1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333,
 '1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333]

In [249]:
(3* list1)/3  #this will give an error
#not valid statement,

TypeError: ignored

In [250]:
#append method for lists
list1.append("a") #will add "a" at the end of the list
list1.append( [ 3, "9"] ) # you can append any datatype object, try with int,str,float etc by yourself 

In [251]:
list1

['1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333,
 'a',
 [3, '9']]

In [252]:
#few methods of list that are handy
'''
1) append() - takes one input, that input is added to the end of the list
2) pop() - takes index position as an input, removes the object from memory at that index and returns the object, If no index given, it will remove the object at -1 index (last object in list)
3) index - takes one input and returns the index of the input in given array
'''
#read more here - https://www.w3schools.com/python/python_ref_list.asp


list1.index(333)

7

In [253]:
list1

['1',
 3,
 'a',
 '1223829382y3827',
 0.002,
 'vv',
 '333',
 333,
 '333',
 333,
 'a',
 [3, '9']]

In [254]:
animals = ['cat', 'dog', 'monkey']

In [255]:
#print values in the list.. 

any_random_name = animals.pop() #removes 'monkey' from list and stored it in variable `any_random_name`
animals

['cat', 'dog']

In [256]:
###Tuple and List are very similar datastructures. Only difference is that tuple is immutable (you cant edit it after defining)

animals = ('cat', 'dog', 'monkey') 
animals[1] = "elephant" #will give error because tuple is immutable.. 

TypeError: ignored

#Dictionary


Very useful datatype, keys are in left, values at right..

key-value pair, keys need to be unique

In [257]:
player_price = [17,13,19] #price in lakhs
player_name = ["sechin trendulkar","gautam gembhir","M doni"] 

player_price[player_name.index("gautam gembhir")] 

13

In [258]:
# but this is pain right?

In [259]:
price_book = {"sechin trendulkar": 17}

In [260]:

price_book["gautam gembhir"] = 13
price_book["M doni"] =19

dir(price_book)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [261]:
#iteration in dictionary


#If elif else



```
if x:
    if y:
        code-statement
elif z:
    another-code-statement
else:
    another-code-statement
```



In [262]:
if True:
  print("OMG this is true!")

OMG this is true!


In [263]:
if  False:
  print("OMG this is false")

In [264]:
if 1:
  print("OMG this is 1")

OMG this is 1


In [265]:
if not 0:
  print("OMG this is `not 0`")

OMG this is `not 0`


In [266]:
if -1:
  print("true condition print hoga") #guess kro bhai 
else:
  print("false condition print hoga")

true condition print hoga


In [267]:
x = True 

if x:
    print('x was True!')
else:
    print('I will be printed in any case where x is not true')

x was True!


In [268]:
var = "a"

if var =="a":
  print("var is a")
elif var == "b":
  print("var is b")
else: 
  print("Var is not a nor b")

var is a


#Loops 

#Functions

In [269]:
def identity(input): #this identity function expects one object as an input; returns same thing, does nothing
  return input

In [294]:
z1 = identity("something")
print(z1)

random_list = [1,2,3.4,"hello"]
z2 = identity(random_list) #here you can see we have passed a list object to the identity function.
print(z2)

something
[1, 2, 3.4, 'hello']


In [295]:
def add_numbers(x=0, y=0 ): #in this function by default the input parameters are set to 0.
    return x+y

In [296]:
print(type(add_numbers))
print(add_numbers)

<class 'function'>
<function add_numbers at 0x7f99d2253dd0>


In [297]:
print(add_numbers(x=1,y=24))
print(add_numbers())

25
0


In [298]:
new_func = add_numbers

new_func(x=1,y=24)

25

In [299]:
id(new_func) == id(add_numbers)


True

In [300]:
#what if there are multiple inputs,add 5 numbers 

In [301]:
def add_n_numbers(*args): #non keyword argument 
  sum=0
  print(args, type(args))
  for i in args:
    sum = sum+i
  return sum

In [302]:
def add_n_numbers(*another_var):
  sum=0
  for i in another_var:
    sum = sum+i
  return sum

In [303]:
add_n_numbers(1,2,33,5,6,67,4)

118

In [304]:
visited_places = ["delhi", "chennai", "shillong", "Bits Pilani K K Birla Goa Campus"]

def last_visited(*args):
  print(args)
  return args[-1]

In [305]:
last_visited(*visited_places) #using a star before a list unpacks the objects in the list

('delhi', 'chennai', 'shillong', 'Bits Pilani K K Birla Goa Campus')


'Bits Pilani K K Birla Goa Campus'

In [306]:
def full_name(**kwargs):
  print(kwargs)
  return kwargs["name"]+kwargs["middle_name"]+ kwargs["last_name"]

In [307]:
full_name(name = "ram ", last_name="patil",middle_name="shyam ")

{'name': 'ram ', 'last_name': 'patil', 'middle_name': 'shyam '}


'ram shyam patil'

In [308]:
#list comprehension and lambda functions

#List of alphabets- normal way..

alphabets = []
for i in range(65,91):
  alphabets.append(chr(i))
alphabets



['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

In [309]:
# using list comprehension 

alphabets = [chr(i) for i in range(65,91)]
alphabets

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

In [310]:
my_func = lambda x,y : x**y
my_func(3,4)

81

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

Numpy is already installed in the google colab; so we dont have to install it seperately .

In [326]:
import numpy 
import numpy as np


In [327]:
a = numpy.array([1, 2, 3])  # Create a rank 1 array
print(a)
a[0] = 5                 # Change an element of the array
print(a)                  

[1 2 3]
[5 2 3]


In [328]:
type(a)

numpy.ndarray

In [329]:
b = numpy.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [330]:
c = np.zeros((2,2))  # Create an array of all zeros
print(c)

[[0. 0.]
 [0. 0.]]


In [331]:
c+2 #2 is added to every element


array([[2., 2.],
       [2., 2.]])

In [332]:
print(a)
print(a+1)

[5 2 3]
[6 3 4]


In [333]:
d = [1,2,3] 

d+1

TypeError: ignored

In [334]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [335]:
#index slicing in numpy
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [337]:
a*3 + 2

array([[ 5,  8, 11, 14],
       [17, 20, 23, 26],
       [29, 32, 35, 38]])